### ISSUE TITLE
A rare mapping canvas freeze bug

### ISSUE THREAD

**Issue by peteihis** [ArtOfIllusion/Polymesh#13]
I've got a feeling that this could have been there for a long time, but I can not repeat it on purpose.

Sometimes the mapping canvas freezes during moving and zooming. The last time it happened, I happened to have console outputs directed to a file and the culprit was 'Array Index Out Of Bounds Exception' in the UVMappingManipulator, when mesh tension was on ..., line 551 or close.

That sounds weird. I wonder if there would be any other way to handle it but a massive try-block and a catch, that just ignores the error?

**Comment by Sailsman63** [comment]
We'll have to keep an eye out. Any commonality between the times that it _did_ happen?

We've also got to get proper logging support for AOI as a whole... Just keep running into stuff that seems more urgent.

**Comment by peteihis** [comment]
Oh, I had still this available. I'll add it here for safe keeping. :)

~~~~txt
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 4
	at artofillusion.polymesh.UVMappingManipulator.mouseDragged(UVMappingManipulator.java:551)
	at artofillusion.polymesh.UVMappingEditorDialog.doMouseDragged(UVMappingEditorDialog.java:1354)
	at artofillusion.polymesh.UVMappingEditorDialog$1.run(UVMappingEditorDialog.java:1320)
	at artofillusion.ui.ActionProcessor$1.run(ActionProcessor.java:46)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at java.awt.Dialog.setVisible(Unknown Source)
	at buoy.widget.Widget.setVisible(Widget.java:156)
	at buoy.widget.WindowWidget.setVisible(WindowWidget.java:174)
	at artofillusion.polymesh.UVMappingEditorDialog.<init>(UVMappingEditorDialog.java:849)
	at artofillusion.polymesh.PolyMeshEditorWindow.doEditMapping(PolyMeshEditorWindow.java:4651)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
~~~~

> Any commonality between the times that it did happen?

Can't really recall far back, but looking at the code (and I said wrong above) at line 551 the rotation handle is being dragged, tension is off and the particular mesh node that induced the issue is either pinned or not selected (= not supposed to move).

**Comment by peteihis** [comment]
Had a couple more of these. Always line 551.

I'm still not sure what the exact combination of action is that triggers it but it has something to do with changing selections and zooming & moving. I don't know what is `null` either but I think this can be patched by a bit of _trying and catching_.
